### ISSUE TITLE
NO DATABASE

### ISSUE THREAD

**Issue by toliano** [Osotechcoding/smatechportal#1]
Hi, this is a great job you've done here. Please how do I access the .sql database?

Many Thanks

**Comment by Osotechcoding** [comment]
> Hi, this is a great job you've done here. Please how do I access the .sql database?
> 
> Many Thanks

To access sql schema. Go to eportal/db
Make sure you give this repo a thumbs up

**Comment by toliano** [comment]
Thanks a million boss. 

Sure, million thumbs up and recommendation.

Please can you show me through on how I can configure the database file?

Many thanks
