### ISSUE TITLE
LOGIN CREDENTIALS

### ISSUE THREAD

**Issue by toliano** [Osotechcoding/smatechportal#2]
Greetings and thanks for the last time. Please how do I get thee login credentials for the admin?

Many thanks in advance

**Comment by Osotechcoding** [comment]
Visit localhost/eportal/adminlogin
Email ***@***.***
Password = smapp123

**Comment by toliano** [comment]
Wow!!! This is really really so awesome. This is a very great job, well responsive and great GUI. Thanks a million for this.
Please I have a few questions:

1. The password given was for the DIRECTOR only and does the DIRECTOR and the ADMIN have the same privilege?
2.  Before making any changes, it always ask for AUTH CODE. How do I get one please?
3. From the DIRECTOR's account, there is no way I can create scratch cards for use.
4. Is there a different password for the admin's account?

Thanks a million for your quick response. Your project is so great.

**Comment by Osotechcoding** [comment]
to have the full privilege you have purchase the Smatech full version
Thanks

**Comment by toliano** [comment]
Please how much does it cost?
